#-------------------------
# LOCAL
# application-local.yml
#-------------------------

spring:
  #-------------------------
  # spring.h2
  #-------------------------
  h2.console.enabled: true
  #-------------------------
  # spring.datasource
  #-------------------------
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:~/trip;MODE=MYSQL
    url: jdbc:h2:mem:trip;MODE=MYSQL
    username: sa
    password:
  #-------------------------
  # spring.jpa
  #-------------------------
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect


#-------------------------
# logging
#-------------------------
logging:
  config: classpath:log4j2-local.xml

file.upload.location: ./files

