#-------------------------
# DEV
# application-dev.yml
#-------------------------


spring:
  #-------------------------
  # spring.datasource
  #-------------------------
  datasource:
    url: jdbc:mariadb://152.67.204.40:3306/trip
    username: trip
    password: trip1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 30000
      connection-test-query: SELECT 1
  #-------------------------
  # spring.jpa
  #-------------------------
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

#-------------------------
# logging
#-------------------------
logging:
  config: classpath:log4j2-local.xml

file.upload.location: /data